scrape_configs:
  - job_name: 'micro-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '192.168.1.111:9080', '192.168.1.111:9082', '192.168.1.111:9083', '192.168.1.111:9089' ]

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '192.168.1.111:8080' ]

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '192.168.1.111:9000' ]

  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '192.168.1.111:9999' ]